### ISSUE TITLE
Npm exits on build

### ISSUE THREAD

**Issue by joakimunge** [natcl/node-rpi-ws281x-native#1]
Tried building this to make everything work with RPi3 B+, I get errors from npm when trying to build it.

Any idea?

Log:

```bash

> rpi-ws281x-native@0.8.2 install /home/pi/dev/natcl_pxl
> node-gyp rebuild -j4 --release

make: Entering directory '/home/pi/dev/natcl_pxl/build'
  AR(target) Release/obj.target/rpi_libws2811.a
  COPY Release/rpi_libws2811.a
make: *** No rule to make target '../src/rpi_ws281x/version', needed by 'src/rpi_ws281x/version.h'.  Stop.
make: Leaving directory '/home/pi/dev/natcl_pxl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-j4" "--release"
gyp ERR! cwd /home/pi/dev/natcl_pxl
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpi-ws281x-native@0.8.2 install: `node-gyp rebuild -j4 --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpi-ws281x-native@0.8.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-08-27T14_06_57_760Z-debug.log
pi@raspberrypi:~/dev/natcl_pxl $
```

**Comment by joakimunge** [comment]
Got solved. I hadn't configured node-gyp.
